/**
 * Ships only the icons the app actually draws.
 *
 * `lucide-react-native` is one barrel over about fifteen hundred icons. Metro
 * has no tree-shaking, so importing three icons from it pulls in all of them —
 * roughly two megabytes of SVG path data that no screen ever renders, on every
 * cold start, on a phone. This reads the package's own export map, finds the
 * icons the source imports by name, and writes a barrel with just those.
 *
 * It runs from metro.config.js on every start, so it cannot go stale: add an
 * icon to a screen and the next bundle contains it.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PKG = path.join(ROOT, 'node_modules', 'lucide-react-native');
const BARREL = path.join(PKG, 'dist', 'esm', 'lucide-react-native.js');
const OUT_DIR = path.join(ROOT, 'stubs', 'lucide-pkg');
const OUT = path.join(OUT_DIR, 'index.js');

const SOURCE_DIRS = ['app', 'components', 'hooks', 'lib', 'providers', 'theme'];

/** Every exported name, mapped to the file that defines it — aliases included. */
function exportMap() {
  const src = fs.readFileSync(BARREL, 'utf8');
  const map = new Map();
  const line = /export\s*\{([^}]*)\}\s*from\s*'([^']+)'/g;
  let m;
  while ((m = line.exec(src))) {
    const file = m[2];
    for (const part of m[1].split(',')) {
      const as = part.split(/\s+as\s+/);
      const name = (as[1] ?? as[0]).trim();
      if (name && !map.has(name)) map.set(name, file);
    }
  }
  return map;
}

function sourceFiles(dir, found = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) sourceFiles(p, found);
    else if (/\.(ts|tsx)$/.test(entry.name)) found.push(p);
  }
  return found;
}

/** The icon names the app imports, across single- and multi-line imports. */
function usedIcons() {
  const wanted = new Set();
  /* A specifier list holds no closing brace, so `[^}]` both crosses the line
     breaks of a multi-line import and stops it swallowing the imports above. */
  const importFrom = /import\s+(?:type\s+)?\{([^}]*)\}\s*from\s*'lucide-react-native'/g;

  for (const dir of SOURCE_DIRS) {
    const full = path.join(ROOT, dir);
    if (!fs.existsSync(full)) continue;
    for (const file of sourceFiles(full)) {
      const src = fs.readFileSync(file, 'utf8');
      let m;
      while ((m = importFrom.exec(src))) {
        for (const part of m[1].split(',')) {
          const spec = part.trim();
          // `type LucideIcon` is erased before the bundle exists.
          if (!spec || /^type\s/.test(spec)) continue;
          wanted.add(spec.split(/\s+as\s+/)[0].trim());
        }
      }
    }
  }
  return [...wanted].sort();
}

function build() {
  const map = exportMap();
  const wanted = usedIcons();

  const missing = wanted.filter((name) => !map.has(name));
  if (missing.length) {
    throw new Error(
      `lucide-react-native has no export named ${missing.join(', ')} — ` +
        'check the spelling, or the icon was renamed in this version.',
    );
  }

  const rel = path
    .relative(OUT_DIR, path.join(PKG, 'dist', 'esm'))
    .split(path.sep)
    .join('/');

  const lines = wanted.map((name) => {
    const file = map.get(name).replace(/^\.\//, '');
    return `export { default as ${name} } from '${rel}/${file}';`;
  });

  const body = [
    '/* Generated by scripts/slim-lucide.js on every Metro start — do not edit. */',
    `/* ${wanted.length} of ${map.size} exported names. */`,
    '',
    ...lines,
    '',
  ].join('\n');

  fs.mkdirSync(OUT_DIR, { recursive: true });
  if (!fs.existsSync(OUT) || fs.readFileSync(OUT, 'utf8') !== body) {
    fs.writeFileSync(OUT, body);
  }
  return { entry: OUT, count: wanted.length, total: map.size };
}

module.exports = { build };

if (require.main === module) {
  const { count, total } = build();
  console.log(`  lucide: ${count} icons kept of ${total} exported names`);
}
