-- ============================================================
-- 0907/02 — The teams people support
--
-- Reference data, not demo data: the picker is empty without it, and an empty
-- picker at sign-up teaches everyone to add a custom row, which is exactly the
-- moderation problem the curated flag exists to avoid.
--
-- The list is deliberately weighted to where AceAiX's athletes are — the Gulf,
-- Iran, North Africa — and then to the clubs a teenager anywhere names first.
-- It is a starting point; `add_custom_team` covers the rest, and curating those
-- additions is how this list should grow.
--
-- Sport is what the club plays, not a filter on who may pick it: a swimmer is
-- allowed to support Liverpool, so the picker does not narrow by the athlete's
-- own sport.
-- ============================================================

insert into public.teams (name, short_name, sport, country, is_curated)
select v.name, v.short_name, v.sport, v.country, true
from (values
  ('Real Madrid', 'RMA', 'Football', 'Spain'),
  ('FC Barcelona', 'BAR', 'Football', 'Spain'),
  ('Atlético Madrid', 'ATM', 'Football', 'Spain'),
  ('Sevilla FC', 'SEV', 'Football', 'Spain'),
  ('Manchester United', 'MUN', 'Football', 'England'),
  ('Manchester City', 'MCI', 'Football', 'England'),
  ('Liverpool FC', 'LIV', 'Football', 'England'),
  ('Arsenal FC', 'ARS', 'Football', 'England'),
  ('Chelsea FC', 'CHE', 'Football', 'England'),
  ('Tottenham Hotspur', 'TOT', 'Football', 'England'),
  ('Bayern München', 'FCB', 'Football', 'Germany'),
  ('Borussia Dortmund', 'BVB', 'Football', 'Germany'),
  ('Juventus', 'JUV', 'Football', 'Italy'),
  ('Inter Milan', 'INT', 'Football', 'Italy'),
  ('AC Milan', 'MIL', 'Football', 'Italy'),
  ('SSC Napoli', 'NAP', 'Football', 'Italy'),
  ('AS Roma', 'ROM', 'Football', 'Italy'),
  ('Paris Saint-Germain', 'PSG', 'Football', 'France'),
  ('Olympique de Marseille', 'OM', 'Football', 'France'),
  ('Olympique Lyonnais', 'OL', 'Football', 'France'),
  ('AFC Ajax', 'AJA', 'Football', 'Netherlands'),
  ('PSV Eindhoven', 'PSV', 'Football', 'Netherlands'),
  ('SL Benfica', 'SLB', 'Football', 'Portugal'),
  ('FC Porto', 'POR', 'Football', 'Portugal'),
  ('Sporting CP', 'SCP', 'Football', 'Portugal'),
  ('Celtic FC', 'CEL', 'Football', 'Scotland'),
  ('Rangers FC', 'RAN', 'Football', 'Scotland'),
  ('Galatasaray', 'GS', 'Football', 'Türkiye'),
  ('Fenerbahçe', 'FB', 'Football', 'Türkiye'),
  ('Beşiktaş', 'BJK', 'Football', 'Türkiye'),
  ('Al Ain FC', 'AIN', 'Football', 'United Arab Emirates'),
  ('Al Wasl FC', 'WSL', 'Football', 'United Arab Emirates'),
  ('Al Nasr SC', 'NSR', 'Football', 'United Arab Emirates'),
  ('Shabab Al Ahli', 'SAH', 'Football', 'United Arab Emirates'),
  ('Al Jazira Club', 'JAZ', 'Football', 'United Arab Emirates'),
  ('Sharjah FC', 'SHJ', 'Football', 'United Arab Emirates'),
  ('Al Wahda FC', 'WAH', 'Football', 'United Arab Emirates'),
  ('Baniyas SC', 'BAN', 'Football', 'United Arab Emirates'),
  ('Al Hilal SFC', 'HIL', 'Football', 'Saudi Arabia'),
  ('Al Nassr FC', 'NAS', 'Football', 'Saudi Arabia'),
  ('Al Ittihad Club', 'ITT', 'Football', 'Saudi Arabia'),
  ('Al Ahli Saudi FC', 'AHL', 'Football', 'Saudi Arabia'),
  ('Al Sadd SC', 'SAD', 'Football', 'Qatar'),
  ('Al Duhail SC', 'DUH', 'Football', 'Qatar'),
  ('Al Arabi SC', 'ARB', 'Football', 'Qatar'),
  ('Al Ahly SC', 'AHY', 'Football', 'Egypt'),
  ('Zamalek SC', 'ZAM', 'Football', 'Egypt'),
  ('Espérance de Tunis', 'EST', 'Football', 'Tunisia'),
  ('Raja Club Athletic', 'RCA', 'Football', 'Morocco'),
  ('Wydad AC', 'WAC', 'Football', 'Morocco'),
  ('Kuwait SC', 'KSC', 'Football', 'Kuwait'),
  ('Persepolis FC', 'PER', 'Football', 'Iran'),
  ('Esteghlal FC', 'EST-IR', 'Football', 'Iran'),
  ('Sepahan SC', 'SEP', 'Football', 'Iran'),
  ('Tractor SC', 'TRC', 'Football', 'Iran'),
  ('Foolad FC', 'FOO', 'Football', 'Iran'),
  ('CR Flamengo', 'FLA', 'Football', 'Brazil'),
  ('SE Palmeiras', 'PAL', 'Football', 'Brazil'),
  ('São Paulo FC', 'SAO', 'Football', 'Brazil'),
  ('Boca Juniors', 'BOC', 'Football', 'Argentina'),
  ('River Plate', 'RIV', 'Football', 'Argentina'),
  ('Club América', 'AME', 'Football', 'Mexico'),
  ('Inter Miami CF', 'MIA', 'Football', 'United States'),
  ('LA Galaxy', 'LAG', 'Football', 'United States'),
  ('Kaizer Chiefs', 'KC', 'Football', 'South Africa'),
  ('Enyimba FC', 'ENY', 'Football', 'Nigeria'),
  ('United Arab Emirates', 'UAE', 'Football', 'United Arab Emirates'),
  ('Iran', 'IRN', 'Football', 'Iran'),
  ('Saudi Arabia', 'KSA', 'Football', 'Saudi Arabia'),
  ('Qatar', 'QAT', 'Football', 'Qatar'),
  ('Morocco', 'MAR', 'Football', 'Morocco'),
  ('Egypt', 'EGY', 'Football', 'Egypt'),
  ('Nigeria', 'NGA', 'Football', 'Nigeria'),
  ('Brazil', 'BRA', 'Football', 'Brazil'),
  ('Argentina', 'ARG', 'Football', 'Argentina'),
  ('France', 'FRA', 'Football', 'France'),
  ('England', 'ENG', 'Football', 'England'),
  ('Portugal', 'POR-NT', 'Football', 'Portugal'),
  ('Spain', 'ESP', 'Football', 'Spain'),
  ('Germany', 'GER', 'Football', 'Germany'),
  ('Japan', 'JPN', 'Football', 'Japan'),
  ('Los Angeles Lakers', 'LAL', 'Basketball', 'United States'),
  ('Golden State Warriors', 'GSW', 'Basketball', 'United States'),
  ('Boston Celtics', 'BOS', 'Basketball', 'United States'),
  ('Chicago Bulls', 'CHI', 'Basketball', 'United States'),
  ('Miami Heat', 'MIA-B', 'Basketball', 'United States'),
  ('Real Madrid Baloncesto', 'RMB', 'Basketball', 'Spain'),
  ('FC Barcelona Bàsquet', 'BARB', 'Basketball', 'Spain'),
  ('Anadolu Efes', 'EFES', 'Basketball', 'Türkiye'),
  ('Al Riyadi Beirut', 'RIY', 'Basketball', 'Lebanon'),
  ('Zamalek Basketball', 'ZAMB', 'Basketball', 'Egypt'),
  ('Al Ahli Dubai Basketball', 'AHD', 'Basketball', 'United Arab Emirates'),
  ('Mumbai Indians', 'MI', 'Cricket', 'India'),
  ('Chennai Super Kings', 'CSK', 'Cricket', 'India'),
  ('Royal Challengers Bengaluru', 'RCB', 'Cricket', 'India'),
  ('Kolkata Knight Riders', 'KKR', 'Cricket', 'India'),
  ('India', 'IND', 'Cricket', 'India'),
  ('Pakistan', 'PAK', 'Cricket', 'Pakistan'),
  ('Australia', 'AUS', 'Cricket', 'Australia'),
  ('England', 'ENG-CR', 'Cricket', 'England'),
  ('United Arab Emirates', 'UAE-CR', 'Cricket', 'United Arab Emirates')
) as v(name, short_name, sport, country)
on conflict do nothing;
